### ISSUE TITLE
Stop out-of-control logs

### ISSUE THREAD

**Issue by indolering** [bluejamesbond/Scribe.js#4] opened 2014-02-13 01:20 UTC
Watching the size of old logs and enabling compaction would be pretty swell.

**Comment by bluejamesbond** [comment] 2015-01-19 04:33
@guillaumewuip Agreed. i will close this issue for now. If you feel the issue is still pertinent to us at the moment, you can open it.

**Closed by bluejamesbond** 2015-01-19 04:33 UTC
